Awesome books: with ES6
maov19/awesome_books_es6 pull request #1
Opened 2023-02-20 10:08 UTC by maov19

Following features were added:

- ES6 syntax re-factoring
1. Divided your code into modules.
2. Created a separate file for each module in the modules directory.
3. Imported Books modules into the index.js file. 
4. Refactored your functions to arrow functions.
5. Kept all functionalities of the app.

- Display the current date below the navigation bar.

1. Downloaded and imported luxon library

2023-02-20 12:29 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @maov19, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-20 12:29 UTC, brainconnect93 commented on modules/Book.js
> +}
- [ ] Great effort working on the awesome book project 👍 , but currently, in your project, I noticed I could not add or remove books, anytime a user tries to add a book using the form in the `add book` section it's not adding and in the `list` section it's not displaying any added book which makes it difficult to remove a book from the list. Kindly fix this

2023-02-21 08:12 UTC, maov19 commented
Dear reviewer, 

The issue observed before was solved. You can see a screen recording below ⬇️ 
Please let me know if there is anything else I should work on.

![awesome_es6](https://user-images.githubusercontent.com/108192399/220285795-a264173e-a914-424c-b8a7-c971624a2193.gif)

2023-02-21 08:25 UTC, Munsa1 approved these changes
Hi @maov19, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 08:27 UTC, merged